VERSION 0.8

VENV:
  FUNCTION
    LOCALLY
      RUN python -m venv venv

DEPS:
  FUNCTION
    LOCALLY
      RUN source venv/bin/activate && pip install -r requirements.txt

INIT:
  FUNCTION
    DO +VENV
    DO +DEPS
